### ISSUE TITLE
Availibility for Alfresco 5.2.x?

### ISSUE THREAD

**Issue by sy-subrc** [keensoft/alfresco-site-home-page-plus#2]
Hi keensoft-team,
we really want to use your plugin but we are running alfresco 5.2.
Will you release a version which supports alfresco 5.2?

Best regards
Harald Schmitz

**Comment by angelborroy-ks** [comment]
Thanks for your interest. This feature has been included in Alfresco OOTB from 5.2 release. 

You can check it at [https://community.alfresco.com/docs/DOC-6366-alfresco-community-edition-201609-ea-release-notes#jive_content_id_Flexible_Site_Dashboards](https://community.alfresco.com/docs/DOC-6366-alfresco-community-edition-201609-ea-release-notes#jive_content_id_Flexible_Site_Dashboards)

**Comment by sy-subrc** [comment]
Many thanks for your fast response and information. Currently we are running 201604-GA but we will check out  201609-EA soon.
